stages:
- name: Install
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: |-
        node -v
        echo `pwd`
- name: Test
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: echo 'Worked'
timeout: 60
notification: {}
